### ISSUE TITLE
static site generation for docs

### ISSUE THREAD

**Issue by artbegolli** [ocibuilder/ocibuilder#15]
Add static site documentation for the ocibuilder/docs repository. Choices can be [Hugo](https://gohugo.io/), [Jekyll](https://jekyllrb.com/), [Statik](https://github.com/rakyll/statik)

**Comment by VaibhavPage** [comment]
MkDocs - material theme

**Comment by artbegolli** [comment]
Priority is to get this done before the end of the sprint - Mkdocs provides the quickest solution with room to have a more in depth docs static site in the future with tools like Hugo
